version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: mqtt_data
      MYSQL_USER: mqtt_user
      MYSQL_PASSWORD: mqttpassword
      TZ: Europe/Brussels
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mqtt_to_mysql/sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mqtt_network

  mqtt_client:
    build:
      context: .
      dockerfile: mqtt_to_mysql/Dockerfile
    image: mqtt-python-client
    container_name: mqtt-python-client
    depends_on:
      - mysql    
      - mosquitto
    networks:
      - mqtt_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "0"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - TZ=Europe/Brussels
    depends_on:
      - mysql
    networks:
      - mqtt_network

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - 1883:1883
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
      - ./mqtt_to_mysql/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqtt_network

volumes:
  mysql_data: null
  mosquitto_data: null
  mosquitto_logs: null

networks:
  mqtt_network:
    driver: bridge