version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - 1883:1883
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
      - ./mqtt_to_mysql/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqtt_network

  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: mqtt_data
      MYSQL_USER: mqtt_user
      MYSQL_PASSWORD: mqttpassword
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mqtt_to_mysql/sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mqtt_network

  adminphp:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-db
      PMA_USER: mqtt_user
      PMA_PASSWORD: mqttpassword
    ports:
      - 8080:8080
    volumes:
      - ./mqtt_to_mysql/apache.conf:/etc/apache2/conf-available/servername.conf
    command: "apache2ctl -D FOREGROUND -f /etc/apache2/conf-available/servername.conf"
    networks:
      - mqtt_network

  mqtt_client:
    build:
      context: ./mqtt_to_mysql
      dockerfile: Dockerfile
    container_name: mqtt-python-client
    depends_on:
      - mysql
      - mosquitto
    networks:
      - mqtt_network

volumes:
  mysql_data: null
  mosquitto_data: null
  mosquitto_logs: null

networks:
  mqtt_network:
    driver: bridge
