version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: mqtt_data
      MYSQL_USER: mqtt_user
      MYSQL_PASSWORD: mqttpassword
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mqtt_to_mysql/sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mqtt_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s  # Startperiod to give MySQL-server time to startup

  mqtt_client:
    build:
      context: ./mqtt_to_mysql
      dockerfile: Dockerfile
    container_name: mqtt-python-client
    depends_on:
      mysql:
        condition: service_healthy
      mosquitto:
        condition: service_started
    networks:
      - mqtt_network

  mosquitto:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - 1883:1883
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
      - ./mqtt_to_mysql/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqtt_network

volumes:
  mysql_data: null
  mosquitto_data: null
  mosquitto_logs: null

networks:
  mqtt_network:
    driver: bridge
